// Auto-generated by scripts/demo.py — do not edit by hand.
import { runGoldenPath } from '../apps/smoke/src/index.ts';

const report = await runGoldenPath();
process.stdout.write(JSON.stringify(report, null, 2));
process.stdout.write('\n');
